//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 02:01:02 PM CET 
//


package rs.ac.uns.ftn.xwsservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTAutor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTAutor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="EMail">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".+@.+\..+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BrojTelefona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ORCID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{4}-d{4}-d{4}-d{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ustanova" type="{http://www.ftn.uns.ac.rs/xws/tim5}CTNaucnaUstanova"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTAutor", propOrder = {
    "ime",
    "prezime",
    "eMail",
    "brojTelefona",
    "orcid",
    "ustanova"
})
public class CTAutor {

    @XmlElement(name = "Ime", required = true)
    protected List<String> ime;
    @XmlElement(name = "Prezime", required = true)
    protected List<String> prezime;
    @XmlElement(name = "EMail", required = true)
    protected String eMail;
    @XmlElement(name = "BrojTelefona", required = true)
    protected String brojTelefona;
    @XmlElement(name = "ORCID", required = true, nillable = true)
    protected String orcid;
    @XmlElement(name = "Ustanova", required = true)
    protected CTNaucnaUstanova ustanova;

    /**
     * Gets the value of the ime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIme() {
        if (ime == null) {
            ime = new ArrayList<String>();
        }
        return this.ime;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prezime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrezime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPrezime() {
        if (prezime == null) {
            prezime = new ArrayList<String>();
        }
        return this.prezime;
    }

    /**
     * Gets the value of the eMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

    /**
     * Gets the value of the brojTelefona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojTelefona() {
        return brojTelefona;
    }

    /**
     * Sets the value of the brojTelefona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojTelefona(String value) {
        this.brojTelefona = value;
    }

    /**
     * Gets the value of the orcid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORCID() {
        return orcid;
    }

    /**
     * Sets the value of the orcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORCID(String value) {
        this.orcid = value;
    }

    /**
     * Gets the value of the ustanova property.
     * 
     * @return
     *     possible object is
     *     {@link CTNaucnaUstanova }
     *     
     */
    public CTNaucnaUstanova getUstanova() {
        return ustanova;
    }

    /**
     * Sets the value of the ustanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTNaucnaUstanova }
     *     
     */
    public void setUstanova(CTNaucnaUstanova value) {
        this.ustanova = value;
    }

}
