//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 02:43:33 PM CET 
//


package rs.ac.uns.ftn.xwsservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTRecenzent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTRecenzent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecenzentID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.ftn.uns.ac.rs/xws/tim5}EnumStatusRecenziranja"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTRecenzent", propOrder = {
    "recenzentID",
    "status"
})
public class CTRecenzent {

    @XmlElement(name = "RecenzentID", required = true)
    protected String recenzentID;
    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected EnumStatusRecenziranja status;

    /**
     * Gets the value of the recenzentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecenzentID() {
        return recenzentID;
    }

    /**
     * Sets the value of the recenzentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecenzentID(String value) {
        this.recenzentID = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EnumStatusRecenziranja }
     *     
     */
    public EnumStatusRecenziranja getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumStatusRecenziranja }
     *     
     */
    public void setStatus(EnumStatusRecenziranja value) {
        this.status = value;
    }

}
