//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.03 at 10:34:01 PM CET 
//


package rs.ac.uns.ftn.xwsservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTRecenzent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTRecenzent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecenzentID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.ftn.uns.ac.rs/xws/tim5}EnumStatusRecenziranja"/>
 *         &lt;element name="Recenzije">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RecenzijaID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTRecenzent", propOrder = {
    "recenzentID",
    "status",
    "recenzije"
})
public class CTRecenzent {

    @XmlElement(name = "RecenzentID", required = true)
    protected String recenzentID;
    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected EnumStatusRecenziranja status;
    @XmlElement(name = "Recenzije", required = true)
    protected Recenzije recenzije;

    /**
     * Gets the value of the recenzentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecenzentID() {
        return recenzentID;
    }

    /**
     * Sets the value of the recenzentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecenzentID(String value) {
        this.recenzentID = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EnumStatusRecenziranja }
     *     
     */
    public EnumStatusRecenziranja getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumStatusRecenziranja }
     *     
     */
    public void setStatus(EnumStatusRecenziranja value) {
        this.status = value;
    }

    /**
     * Gets the value of the recenzije property.
     * 
     * @return
     *     possible object is
     *     {@link Recenzije }
     *     
     */
    public Recenzije getRecenzije() {
        if (recenzije == null) {
            recenzije = new Recenzije();
        }
        return recenzije;
    }

    /**
     * Sets the value of the recenzije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recenzije }
     *     
     */
    public void setRecenzije(Recenzije value) {
        this.recenzije = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RecenzijaID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recenzijaID"
    })
    public static class Recenzije {

        @XmlElement(name = "RecenzijaID", required = true)
        protected List<String> recenzijaID;

        /**
         * Gets the value of the recenzijaID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the recenzijaID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecenzijaID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRecenzijaID() {
            if (recenzijaID == null) {
                recenzijaID = new ArrayList<String>();
            }
            return this.recenzijaID;
        }

    }

}
