//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.20 at 12:46:34 PM CET 
//


package rs.ac.uns.ftn.xwsservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NaslovnaStrana">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Autori">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Autor" type="{naucni_rad}CTAutor" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Abstrakt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="KljucneReci">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="KljucnaRec" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="6" minOccurs="4"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Poglavlja">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Poglavlje" type="{naucni_rad}CTPoglavlje"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Reference">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="Referenca" type="{naucni_rad}CTReferenca"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naslovnaStrana",
    "abstrakt",
    "kljucneReci",
    "poglavlja",
    "reference"
})
@XmlRootElement(name = "NaucniRad")
public class NaucniRad {

    @XmlElement(name = "NaslovnaStrana", required = true)
    protected NaslovnaStrana naslovnaStrana;
    @XmlElement(name = "Abstrakt", required = true)
    protected String abstrakt;
    @XmlElement(name = "KljucneReci", required = true)
    protected KljucneReci kljucneReci;
    @XmlElement(name = "Poglavlja", required = true)
    protected Poglavlja poglavlja;
    @XmlElement(name = "Reference", required = true)
    protected Reference reference;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the naslovnaStrana property.
     * 
     * @return
     *     possible object is
     *     {@link NaslovnaStrana }
     *     
     */
    public NaslovnaStrana getNaslovnaStrana() {
        return naslovnaStrana;
    }

    /**
     * Sets the value of the naslovnaStrana property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaslovnaStrana }
     *     
     */
    public void setNaslovnaStrana(NaslovnaStrana value) {
        this.naslovnaStrana = value;
    }

    /**
     * Gets the value of the abstrakt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstrakt() {
        return abstrakt;
    }

    /**
     * Sets the value of the abstrakt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstrakt(String value) {
        this.abstrakt = value;
    }

    /**
     * Gets the value of the kljucneReci property.
     * 
     * @return
     *     possible object is
     *     {@link KljucneReci }
     *     
     */
    public KljucneReci getKljucneReci() {
        return kljucneReci;
    }

    /**
     * Sets the value of the kljucneReci property.
     * 
     * @param value
     *     allowed object is
     *     {@link KljucneReci }
     *     
     */
    public void setKljucneReci(KljucneReci value) {
        this.kljucneReci = value;
    }

    /**
     * Gets the value of the poglavlja property.
     * 
     * @return
     *     possible object is
     *     {@link Poglavlja }
     *     
     */
    public Poglavlja getPoglavlja() {
        return poglavlja;
    }

    /**
     * Sets the value of the poglavlja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Poglavlja }
     *     
     */
    public void setPoglavlja(Poglavlja value) {
        this.poglavlja = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="KljucnaRec" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="6" minOccurs="4"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kljucnaRec"
    })
    public static class KljucneReci {

        @XmlElement(name = "KljucnaRec", required = true)
        protected List<String> kljucnaRec;

        /**
         * Gets the value of the kljucnaRec property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the kljucnaRec property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKljucnaRec().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getKljucnaRec() {
            if (kljucnaRec == null) {
                kljucnaRec = new ArrayList<String>();
            }
            return this.kljucnaRec;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Autori">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Autor" type="{naucni_rad}CTAutor" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "autori"
    })
    public static class NaslovnaStrana {

        @XmlElement(name = "Naslov", required = true)
        protected String naslov;
        @XmlElement(name = "Autori", required = true)
        protected Autori autori;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the autori property.
         * 
         * @return
         *     possible object is
         *     {@link Autori }
         *     
         */
        public Autori getAutori() {
            return autori;
        }

        /**
         * Sets the value of the autori property.
         * 
         * @param value
         *     allowed object is
         *     {@link Autori }
         *     
         */
        public void setAutori(Autori value) {
            this.autori = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Autor" type="{naucni_rad}CTAutor" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "autor"
        })
        public static class Autori {

            @XmlElement(name = "Autor", required = true)
            protected List<CTAutor> autor;

            /**
             * Gets the value of the autor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the autor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CTAutor }
             * 
             * 
             */
            public List<CTAutor> getAutor() {
                if (autor == null) {
                    autor = new ArrayList<CTAutor>();
                }
                return this.autor;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Poglavlje" type="{naucni_rad}CTPoglavlje"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "poglavlje"
    })
    public static class Poglavlja {

        @XmlElement(name = "Poglavlje", required = true)
        protected CTPoglavlje poglavlje;

        /**
         * Gets the value of the poglavlje property.
         * 
         * @return
         *     possible object is
         *     {@link CTPoglavlje }
         *     
         */
        public CTPoglavlje getPoglavlje() {
            return poglavlje;
        }

        /**
         * Sets the value of the poglavlje property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTPoglavlje }
         *     
         */
        public void setPoglavlje(CTPoglavlje value) {
            this.poglavlje = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Referenca" type="{naucni_rad}CTReferenca"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "referenca"
    })
    public static class Reference {

        @XmlElement(name = "Referenca", required = true)
        protected List<CTReferenca> referenca;

        /**
         * Gets the value of the referenca property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the referenca property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReferenca().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CTReferenca }
         * 
         * 
         */
        public List<CTReferenca> getReferenca() {
            if (referenca == null) {
                referenca = new ArrayList<CTReferenca>();
            }
            return this.referenca;
        }

    }

}
