//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.21 at 06:33:51 PM CET 
//


package rs.ac.uns.ftn.xwsservice.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xswservice.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CTPasusTabela_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/tim5", "Tabela");
    private final static QName _CTPasusSlika_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/tim5", "Slika");
    private final static QName _CTPasusLista_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/tim5", "Lista");
    private final static QName _CTPasusTekst_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/tim5", "Tekst");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xswservice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NaucniRad }
     * 
     */
    public NaucniRad createNaucniRad() {
        return new NaucniRad();
    }

    /**
     * Create an instance of {@link CTPasus }
     * 
     */
    public CTPasus createCTPasus() {
        return new CTPasus();
    }

    /**
     * Create an instance of {@link CTPasus.Tabela }
     * 
     */
    public CTPasus.Tabela createCTPasusTabela() {
        return new CTPasus.Tabela();
    }

    /**
     * Create an instance of {@link NaucniRad.NaslovnaStrana }
     * 
     */
    public NaucniRad.NaslovnaStrana createNaucniRadNaslovnaStrana() {
        return new NaucniRad.NaslovnaStrana();
    }

    /**
     * Create an instance of {@link NaucniRad.KljucneReci }
     * 
     */
    public NaucniRad.KljucneReci createNaucniRadKljucneReci() {
        return new NaucniRad.KljucneReci();
    }

    /**
     * Create an instance of {@link NaucniRad.Poglavlja }
     * 
     */
    public NaucniRad.Poglavlja createNaucniRadPoglavlja() {
        return new NaucniRad.Poglavlja();
    }

    /**
     * Create an instance of {@link NaucniRad.Reference }
     * 
     */
    public NaucniRad.Reference createNaucniRadReference() {
        return new NaucniRad.Reference();
    }

    /**
     * Create an instance of {@link PropratnoPismo }
     * 
     */
    public PropratnoPismo createPropratnoPismo() {
        return new PropratnoPismo();
    }

    /**
     * Create an instance of {@link CTAutor }
     * 
     */
    public CTAutor createCTAutor() {
        return new CTAutor();
    }

    /**
     * Create an instance of {@link CTReferenca }
     * 
     */
    public CTReferenca createCTReferenca() {
        return new CTReferenca();
    }

    /**
     * Create an instance of {@link CTPoglavlje }
     * 
     */
    public CTPoglavlje createCTPoglavlje() {
        return new CTPoglavlje();
    }

    /**
     * Create an instance of {@link CTNaucnaUstanova }
     * 
     */
    public CTNaucnaUstanova createCTNaucnaUstanova() {
        return new CTNaucnaUstanova();
    }

    /**
     * Create an instance of {@link CTAdresa }
     * 
     */
    public CTAdresa createCTAdresa() {
        return new CTAdresa();
    }

    /**
     * Create an instance of {@link CTPasus.Slika }
     * 
     */
    public CTPasus.Slika createCTPasusSlika() {
        return new CTPasus.Slika();
    }

    /**
     * Create an instance of {@link CTPasus.Lista }
     * 
     */
    public CTPasus.Lista createCTPasusLista() {
        return new CTPasus.Lista();
    }

    /**
     * Create an instance of {@link CTPasus.Tekst }
     * 
     */
    public CTPasus.Tekst createCTPasusTekst() {
        return new CTPasus.Tekst();
    }

    /**
     * Create an instance of {@link CTPasus.Tabela.Red }
     * 
     */
    public CTPasus.Tabela.Red createCTPasusTabelaRed() {
        return new CTPasus.Tabela.Red();
    }

    /**
     * Create an instance of {@link NaucniRad.NaslovnaStrana.Autori }
     * 
     */
    public NaucniRad.NaslovnaStrana.Autori createNaucniRadNaslovnaStranaAutori() {
        return new NaucniRad.NaslovnaStrana.Autori();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPasus.Tabela }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/tim5", name = "Tabela", scope = CTPasus.class)
    public JAXBElement<CTPasus.Tabela> createCTPasusTabela(CTPasus.Tabela value) {
        return new JAXBElement<CTPasus.Tabela>(_CTPasusTabela_QNAME, CTPasus.Tabela.class, CTPasus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPasus.Slika }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/tim5", name = "Slika", scope = CTPasus.class)
    public JAXBElement<CTPasus.Slika> createCTPasusSlika(CTPasus.Slika value) {
        return new JAXBElement<CTPasus.Slika>(_CTPasusSlika_QNAME, CTPasus.Slika.class, CTPasus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPasus.Lista }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/tim5", name = "Lista", scope = CTPasus.class)
    public JAXBElement<CTPasus.Lista> createCTPasusLista(CTPasus.Lista value) {
        return new JAXBElement<CTPasus.Lista>(_CTPasusLista_QNAME, CTPasus.Lista.class, CTPasus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPasus.Tekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/tim5", name = "Tekst", scope = CTPasus.class)
    public JAXBElement<CTPasus.Tekst> createCTPasusTekst(CTPasus.Tekst value) {
        return new JAXBElement<CTPasus.Tekst>(_CTPasusTekst_QNAME, CTPasus.Tekst.class, CTPasus.class, value);
    }

}
