//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.03 at 10:34:01 PM CET 
//


package rs.ac.uns.ftn.xwsservice.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTipRada.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTipRada">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="naucni-rad"/>
 *     &lt;enumeration value="tehnicki-rad"/>
 *     &lt;enumeration value="pregledni-rad"/>
 *     &lt;enumeration value="teza"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TTipRada")
@XmlEnum
public enum TTipRada {

    @XmlEnumValue("naucni-rad")
    NAUCNI_RAD("naucni-rad"),
    @XmlEnumValue("tehnicki-rad")
    TEHNICKI_RAD("tehnicki-rad"),
    @XmlEnumValue("pregledni-rad")
    PREGLEDNI_RAD("pregledni-rad"),
    @XmlEnumValue("teza")
    TEZA("teza");
    private final String value;

    TTipRada(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipRada fromValue(String v) {
        for (TTipRada c: TTipRada.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
