//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 05:38:46 PM CET 
//


package rs.ac.uns.ftn.xswservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTKomentar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTKomentar">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KomentariAutor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KomentariUrednik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReferenciraniElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTKomentar", propOrder = {
    "komentariAutor",
    "komentariUrednik",
    "referenciraniElement"
})
public class CTKomentar {

    @XmlElement(name = "KomentariAutor", required = true)
    protected String komentariAutor;
    @XmlElement(name = "KomentariUrednik", required = true)
    protected String komentariUrednik;
    @XmlElement(name = "ReferenciraniElement", required = true)
    protected String referenciraniElement;

    /**
     * Gets the value of the komentariAutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentariAutor() {
        return komentariAutor;
    }

    /**
     * Sets the value of the komentariAutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentariAutor(String value) {
        this.komentariAutor = value;
    }

    /**
     * Gets the value of the komentariUrednik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentariUrednik() {
        return komentariUrednik;
    }

    /**
     * Sets the value of the komentariUrednik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentariUrednik(String value) {
        this.komentariUrednik = value;
    }

    /**
     * Gets the value of the referenciraniElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenciraniElement() {
        return referenciraniElement;
    }

    /**
     * Sets the value of the referenciraniElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenciraniElement(String value) {
        this.referenciraniElement = value;
    }

}
